#!/usr/bin/env python
import os
import sys
import jinja2
"""
Refresh the file served by the http server with all the graphs present.
"""
graphs = []
INDEX_FILE = sys.argv[1]
WWW_DATA_DIR = sys.argv[2]
CURRENT_DIR = sys.argv[3]

for date in sys.stdin.read().splitlines():
    fname = os.path.join(WWW_DATA_DIR, date, "viz.png")
    img_path = "{}/viz.png".format(date)
    if os.path.isfile(fname):
        graphs.append({'date': date, 'fname': img_path})

loader = jinja2.FileSystemLoader(CURRENT_DIR)
env = jinja2.Environment(loader=loader)

with open(INDEX_FILE, "w+") as outf:
    outf.write(env.get_template("stats_template.html").render(graphs=graphs))

sys.exit(0)
